### ISSUE TITLE
Get CSI2 data without I2C

### ISSUE THREAD

**Issue by remusmp** [raspberrypi/raspiraw#77]
Hello,

Is it possible to get the CSI2 data without any I2C interaction? 
I am dealing with an experimental camera that has no I2C lines - it's still under development and all settings are hardcoded on the camera side. All I know is that it always outputs MIPI CSI2 data and it has no I2C.
Should I attempt to customize raspiraw and bypass all I2C interactions or is there more to it?

Many thanks!

**Comment by 6by9** [comment]
I would recommend you use the kernel bcm2835_unicam driver rather than raspiraw. 

Without knowing information about what form of CSI2 data it outputs, then you're going to have some problems.
CSI2 packets have a data type field that designates either signalling or the image format (YUYV, RAW8, 10, 12, 14, 16, RGB, etc). The receiver must be told the correct data type for the image data, otherwise it will be discarded. It also needs to know the relevant geometry of the image buffer.

I did start on a Linux dummy image sensor driver that would largely just accept any image format and geometry so that the CSI2 receiver was correctly configured. I'll dig it out.

**Comment by 6by9** [comment]
I've dug out the dummy_sensor driver. Now at https://github.com/6by9/linux/tree/rpi-5.15.y-dummy_sensor, and will be a PR fairly soon.

**Comment by remusmp** [comment]
Hello 6by9,

Many thanks for `rpi-5.15.y-dummy_sensor`. It works! Really appreciate it!
